### PR TITLE
Update desired instances to 2

### PR DESCRIPTION
**Pull request by iaimans**
## Description

Update desired instances to 2

## Types of changes

- Infra

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by juanfi — APPROVED** [review]
LGTM

**Review by oscargiol — APPROVED** [review]
LGTM :fox_face:

**Review by cdespona — APPROVED** [review]
LGTM

**Comment by iaimans** [comment]
atlantis apply -p staging

**Comment by iaimans** [comment]
atlantis plan -p prod

**Comment by iaimans** [comment]
atlantis apply -p prod

**Pull request merged**
