### PR TITLE
Project Setup

### PR DESCRIPTION
**Pull request by iaimans**
This PR includes all project setup and is the placeholder to apply the infrastructure

### CODE REVIEW

**Comment by iaimans** [comment]
atlantis plan -p staging

**Comment by iaimans** [comment]
atlantis plan -p prod

**Review by oscargiol — APPROVED** [review]

**Comment by iaimans** [comment]
atlantis plan -p prod

**Comment by iaimans** [comment]
atlantis apply -p staging

**Comment by iaimans** [comment]
atlantis plan -p repository

**Comment by iaimans** [comment]
atlantis plan -p repository

**Comment by iaimans** [comment]
atlantis apply -p repository

**Comment by iaimans** [comment]
atlantis apply -p prod

**Pull request merged**
